# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c03922c44f444e6bf7faccb815ceaa38f52512b39cdb81398a8e40e90945c658b8ef7ef569c748704cb40dc140996c77c3797f4aabc40bd735d58d908d55a82

test:
  secret_key_base: 33947c4ca126d47aa495f1ef87e527dc5875e685f184bdeb399d177682046f8218825557682a7708e36930cb9e71337b1c101c89781e79c0f11da46b7e6fdc3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
