# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86013e9f98334c657f553df45a48a4a80447f7b5609f8fa7d2a96ed047c8043fccd0ddee74e2e3a84948fb71081e8757503132b7c1bf17b6bb1644a62ed8be51

test:
  secret_key_base: 6a59158c92d8a58ef3ba3b317c4e4c6b2b56b5179c194ef2445e2174d4b8dfcb1552d1983951635f821f511df53b3b5bdc6384c0a46e1705c3c0dc66598b62a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
