# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e881f9505063bb982ec09cb99d4920709c2e4119951fb54c4849c0dca9dbae27422d340f31549874623c48f84274daf34e4cbae48cda2fa9dca422ac1f53d790

test:
  secret_key_base: 9fb3de2c716607a816e0effa500abd284e6fb95d564b1a80a810c3049a84eb29d34b533ef33362e19935e07933a0aa06fb34558dc11b0c71cfea36658d8fda69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
